version: '3'
services:
  redis:
    image: 'redis:latest'
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - '8000:8000'
    volumes:
      - app/server/server
      - .:/app
  