version: '3'
services:
  redis:
    image: 'redis'
    ports:
      - '6379:6379'
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile 
    depends_on: 
      - redis
    ports:
      - '8000:8000'
    volumes:
      - .:/app
  